#!/usr/bin/env bash
# Stop hook — appends a structured session log entry and generates daily HTML summary
set -euo pipefail

PAYLOAD=$(cat)
TRANSCRIPT=$(printf '%s' "$PAYLOAD" | python3 -c \
  "import sys,json; d=json.load(sys.stdin); print(d.get('transcript_path',''))" 2>/dev/null || echo "")

LOG_FILE=".claude/session.log"
REPORTS_DIR="reports"
mkdir -p "$REPORTS_DIR" "$(dirname "$LOG_FILE")"

TIMESTAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
DATE_HUMAN=$(date '+%B %d, %Y')
DATE_KEY=$(date '+%Y%m%d')

# Extract session activity from transcript using a temp Python file
# (avoids heredoc-inside-$() which confuses bash on macOS)
SUMMARY="no-activity"
if [[ -n "$TRANSCRIPT" && -f "$TRANSCRIPT" ]]; then
  _PY=$(mktemp /tmp/stop-summary-XXXXXX.py)
  cat > "$_PY" <<'PY'
import sys, json

transcript_path = sys.argv[1]
edited = set()
tests_run = False
deploys = []
audits = []
soql = 0

try:
    with open(transcript_path) as f:
        for line in f:
            try:
                entry = json.loads(line.strip())
            except Exception:
                continue
            content = entry.get("content", [])
            if not isinstance(content, list):
                continue
            for block in content:
                if not isinstance(block, dict):
                    continue
                if block.get("type") != "tool_use":
                    continue
                name  = block.get("name", "")
                inp   = block.get("input", {})
                cmd   = inp.get("command", "")
                fpath = inp.get("file_path", "")

                if name in ("Edit", "Write") and fpath:
                    edited.add(fpath.split("/")[-1])
                if "sf apex run test" in cmd:
                    tests_run = True
                if "sf project deploy" in cmd:
                    parts = cmd.split()
                    target = ""
                    if "--target-org" in parts:
                        idx = parts.index("--target-org")
                        target = parts[idx + 1] if idx + 1 < len(parts) else ""
                    deploys.append(target or "unknown")
                if "org-scan.sh" in cmd or "/org-scan" in cmd:
                    audits.append("org-scan")
                if "sf data query" in cmd and "LoginHistory" in cmd:
                    audits.append("login-history")
                if "sf data query" in cmd:
                    soql += 1
except Exception:
    pass

parts = []
if edited:    parts.append("edited:" + ",".join(sorted(edited)[:5]))
if tests_run: parts.append("tests:run")
if deploys:   parts.append("deploy:" + ",".join(deploys))
if audits:    parts.append("audit:" + ",".join(set(audits)))
if soql:      parts.append("soql:" + str(soql) + "queries")
print(" | ".join(parts) if parts else "no-tool-activity")
PY
  SUMMARY=$(python3 "$_PY" "$TRANSCRIPT" 2>/dev/null || echo "no-activity")
  rm -f "$_PY"
fi

LOG_LINE="${TIMESTAMP} | ${SUMMARY}"
echo "$LOG_LINE" >> "$LOG_FILE"

# Collect today's log lines for HTML
TODAY_LINES=$(grep "^${TIMESTAMP:0:10}" "$LOG_FILE" 2>/dev/null || echo "$LOG_LINE")

ROWS=""
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  TS=$(echo "$line"   | cut -d'|' -f1 | tr -d ' ')
  REST=$(echo "$line" | cut -d'|' -f2- | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')
  ROWS="${ROWS}<tr><td style='color:#64748b;white-space:nowrap;font-family:monospace;font-size:.78rem'>${TS}</td><td>${REST}</td></tr>"
done <<< "$TODAY_LINES"

DAILY_HTML="${REPORTS_DIR}/session-${DATE_KEY}.html"

cat > "$DAILY_HTML" <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Session Summary — ${DATE_HUMAN}</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f8fafc;color:#1e293b;padding:32px}
  h1{font-size:1.3rem;font-weight:700;margin-bottom:4px}
  .sub{color:#64748b;font-size:.85rem;margin-bottom:24px}
  table{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;border:1px solid #e2e8f0;overflow:hidden}
  th{padding:10px 16px;background:#f1f5f9;font-size:.78rem;text-transform:uppercase;
     letter-spacing:.04em;color:#475569;border-bottom:2px solid #e2e8f0;text-align:left}
  td{padding:9px 16px;border-bottom:1px solid #f1f5f9;font-size:.83rem;vertical-align:top}
  tr:last-child td{border-bottom:none}
  footer{margin-top:20px;font-size:.75rem;color:#94a3b8;text-align:center}
</style>
</head>
<body>
<h1>📋 Session Summary — ${DATE_HUMAN}</h1>
<p class="sub">Auto-generated by Claude Code stop hook &nbsp;·&nbsp; Last updated: ${TIMESTAMP}</p>
<table>
  <tr><th style="width:200px">Time (UTC)</th><th>Activity</th></tr>
  ${ROWS:-<tr><td colspan="2" style="text-align:center;color:#94a3b8;padding:20px">No activity recorded yet</td></tr>}
</table>
<footer>Log file: ${LOG_FILE}</footer>
</body>
</html>
HTML

echo ""
echo "📋 Session logged → ${LOG_FILE}"
echo "   Daily summary  → ${DAILY_HTML}"
